### ISSUE TITLE
copr question for the expert

### ISSUE THREAD

**Issue by boydkelly** [google/copr-sundry#193]
Hi,
Just in case you might want to help out with a copr/github question.  I am trying to build a spec file for hugo.  The only issue I see is that there are a bunch of github dependencies in the spec file, that its not finding.
error log:
https://copr-be.cloud.fedoraproject.org/results/boydkelly/hugo/fedora-28-x86_64/00801388-hugo/build.log.gz
spec file:
https://github.com/boydkelly/hugo/blob/master/hugo.spec

What do I have to do to make these dependencies available to copr?

Thanks!

**Comment by vrusinov** [comment]
Sorry - I did not see it in 2018, and I guess it's too late now.
